config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :items, shallow: true
  end

  resources :carts,     only: [:show, :destroy]
  resources :cartitems, only: [:create, :update, :show, :destroy]
  resources :orders

  root to: 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many   :cartitems, dependent: :destroy
  has_many   :items, through: :cartitems

  # Если item уже есть в корзине, то добавляем к его количеству
  # единицу и перезаписываем cartitem. Если нет, создаем cartitem
  def add_item(item_params)
    if self.items.include?(item_params)
      cartitem = self.cartitems.find_by(item: item_params)
      cartitem.quantity += 1
      cartitem.save
    else
      new_cartitem = Cartitem.create(item: item_params, cart: self)
    end

    new_cartitem
  end

  # Общая сумма заказа
  def sub_total
    sum = 0
    self.cartitems.each do |cartitem|
      sum += cartitem.total_price
    end

    sum
  end

  # Общее количество заказов
  def total_items
    self.cartitems.all.map(&:quantity).sum
  end
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  belongs_to :order, optional: true

  # Стоимость нескольких единиц одного товара
  def total_price
    self.quantity * self.item.price
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many   :cartitems, dependent: :destroy
  has_many   :carts, through: :cartitems
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :cartitems, dependent: :destroy
  validates :user_name, :phone, :email, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  private

  def current_cart
    @current_cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  before_action :current_cart, only: %I[update create destroy]
  before_action :set_cart_item, only: %I[update destroy]

  def create
    item = Item.find(params[:item_id])
    cart = @current_cart
    cart.add_item(item)

    if cart.save
      redirect_to cart_path(@current_cart)
    else
      flash[:error] = 'Не удалось добавить товар в карзину'
      redirect_to item_path(item)
    end
  end

  def update
    @cart_item.update_attributes(cartitem_params)
    respond_to do |format|
      format.html { redirect_to cart_path(@current_cart) }
      format.json {render json: @cart_item}
    end
  end

  def destroy
    @cart_item.destroy
    redirect_to cart_path(@current_cart)
  end

  private

  def set_cart_item
    @cart_item = Cartitem.find(params[:id])
  end

  def cartitem_params
    params.require(:cartitem).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %I[show destroy]

  def index
    @categories = Category.all
  end

  def show
    @item = @category.items.build(params[:item])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to 'index'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category, only: %I[create destroy]
  before_action :set_item, only: %I[edit update show destroy]
  before_action :current_cart, except: %I[show]

  def show
  end

  def create
    byebug
    @item = @category.items.build(item_params)
    if @item.save
      redirect_to @category, notice: 'Item created'
    else
      render 'categories/show'
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: 'Item updated'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to category_path
  end

  private

  def set_category
    @category = Category.find(params[:category_id]) if params[:category_id]
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :weight, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @current_cart.cartitems.each do |cartitem|
      @order.cartitems << cartitem
      cartitem.cart_id = nil
    end

    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:user_name, :phone, :email, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/views/carts/show.html.erb
<h2>Корзина</h2> <h3>Товаров: <%= @cart.total_items %></h3>
<br/>
<% if @cart.cartitems.presence %>
    <ul>
      <% @cart.cartitems.each do |cartitem| %>
          <li>Item: <%= cartitem.item.name %>/ Price:
            <p id="price_cartitem_<%= cartitem.id %>" style="display: inline"><%= (cartitem.item.price) %></p> rub/
            Total Price:
            <p id="total_price_cartitem_<%= cartitem.id %>" style="display: inline"><%= (cartitem.total_price) %></p>
            rub
          </li>

          <ul>
            <li>
              <%= form_for cartitem, id: "form", remote: true, :html => {:'data-type' => 'json'} do |f| %>
                  <%= f.number_field :quantity %>
                  <%= f.submit %>
              <% end %>
            </li>
            <br/>
            <li>
              <%= link_to "Remove item", cartitem_path(cartitem), method: :delete %>
            </li>
            <br/>
          </ul>
      <% end %>
    </ul>

    <%= link_to "Очистить корзину", cart_path(@current_cart), method: :delete, data: {confirm: "Вы уверены?"} %>
    <br/>

    <h3>Sub total: <p id="sub_total" style="display: inline"><%= (@cart.sub_total) %></p> rub</h3>
    <br/>
    <%= link_to "Оформить заказ", new_order_path %><br/>
<% else %>
    <p>В вашей корзине пока нет товаров.</p>
<% end %>

<script>
        $(document).ajaxSuccess(function (event, xhr, settings) {
            var respond = $.parseJSON(xhr.responseText);
            var quantity = respond.quantity;
            var cartitem_id = respond.id;
            var price = $('#price_cartitem_' + cartitem_id).text();
            $('#total_price_cartitem_' + cartitem_id).text(quantity * price);

            var sub_total_arr = $('[id*=total_price_cartitem]').map(function () {
                return parseFloat($(this).text());  //посмотри что такое $(this)
            }).toArray();

            var sub_total = sub_total_arr.reduce(function (previousValue, currentItem, index) {
                return previousValue + currentItem
            });

            $('#sub_total').text(sub_total);
            // открыть модальное окно
        })
</script>

app/views/categories/_form.html.erb
<%= form_for @category, html: {multipart: true} do |f| %>
  <%= f.label 'Наименование категории' %><br />
  <%= f.text_field :name %>
  <br />
  <br />
  <%= f.submit 'Сохранить' %> или <%= link_to 'вернуться', :back %>
<% end %>

app/views/categories/index.html.erb
<% title "Categories" %>

<div>
  <h2>Категории товаров <hr /></h2>
  <br />
  <% @categories.each do |category| %>
    <div>
      <h4><%= link_to  category.name, category_path(category) %></h4>
      <%= link_to 'Удалить категорию', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
  <% end %>
  <br />
  <%= link_to "Создать категорию", new_category_url %>
</div>

app/views/categories/new.html.erb
<% title "New Category" %>

<div class="col-lg-3 buffer-top">
  <h2>Создать категорию</h2>

      <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<% title "Category-Items" %>

<div class="col-lg-9">
  <h2 class="buffer-both text-center"><%= @category.name %> <hr /></h2>

  <%= render partial: 'items/category_items' %>

  <%= render partial: 'items/form', locals: {item: @item || @category.items.build} %>
</div>

app/views/items/_category_items.html.erb
<% @category.items.each do |item| %>
  <ul class="list-group list-group-flush">
    <% if item.persisted?  %>
      <li class="list-group-item"><h4><%= link_to item.name, item_path(item) %>
        Вес: <%= item.weight %> Цена: <%= item.price %></h4>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/items/_form.html.erb
<div>
  <%= form_for [@category, @item] do |f| %>
    <p>
    <%= f.label 'Наименование товара' %><br />
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label 'Цена' %><br />
    <%= f.text_field :price %>
    </p>
    <p>
    <%= f.label 'Вес' %><br />
    <%= f.text_field :weight %>
    </p>
    <p>
    <%= f.submit 'Сохранить товар' %> или <%= link_to 'вернуться', :back %>
    </p>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="col-lg-3 buffer-top">
  <h2>Изменить товар</h2>

  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<% title "#{@item.name}" %>

<div class="col-lg-3 buffer-top">
  <div class="table-responsive">
    <table class="table">
      <ul class="lead">
         <li><%= @item.name %></li>
         <li>Вес: <%= @item.weight %> гр.</li>
         <li>Цена: <%= @item.price %> руб.</li>
         <li><%= button_to "добавить #{@item.name} в корзину", cartitems_path(item_id: @item.id) %></li>
         <li><%= link_to 'Обновить', edit_item_path(@item.category) %></li>
         <li><%= link_to 'Удалить', item_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp - <%= content_for?(:title) ? yield(:title) : 'The Biggest Online Store on Earth' %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order, html: {multipart: true} do |f| %>
  <p>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/index.html.erb
<h2>All Orders</h2>

<% @orders.each do |order| %>
  <p>Name:  <%= order.user_name %></p>
  <p>Phone: <%= order.phone %></p>
  <p>Email: <%= order.email %></p>
  <p>Line Items: </p>
  <ul>
    <% order.cartitems.each do |cartitem| %>
    <li><%= cartitem.quantity %> x <%= cartitem.item.name %></li>
    <% end %>
  </ul>

   <p><%= link_to 'Удалить', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/orders/new.html.erb
<% title "New Order" %>

<div class="col-lg-3 buffer-top">
  <h2>Оформить заказ</h2>
  <%= render 'form' %>
</div>